name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call API endpoint
        run: |
          curl "https://taegificbot.vercel.app/api/recommend?query=angst"
